version: "3.9"

services:
  server:
    build: ./server
    container_name: server
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./server:/app
    command: npm run dev

  client:
    build: ./client
    container_name: client
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
    command: npm start
    depends_on:
      - server

  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
